import { createRequire } from 'node:module'

async function main() {
  const require = createRequire(import.meta.url)
  const { chromium } = require(process.env.PLAYWRIGHT_MODULE!)
  const browser = await chromium.launch({ channel: 'chrome', headless: true })
  try {
    const page = await browser.newPage()
    const errors: string[] = []
    page.on('pageerror', (error: Error) => errors.push(error.message))
    for (const [width, height] of [[1440, 950], [390, 844]]) {
      await page.setViewportSize({ width, height })
      await page.goto(process.env.COMPONENTS_PREVIEW_URL ?? 'http://127.0.0.1:5176/tests/ui/components-preview.html')
      const input = page.getByRole('combobox', { name: 'Message' })
      await input.waitFor()
      const pick = page.getByRole('button', { name: 'Select component in the page', exact: true })
      await input.fill('Check this')
      await input.press('Home')
      for (let i = 0; i < 6; i++)
        await input.press('ArrowRight')
      await pick.click()
      await page.getByRole('button', { name: 'Cancel component selection', exact: true }).waitFor()
      const target = page.getByRole('button', { name: 'Home', exact: true })
      await target.hover()
      await page.waitForFunction(() => document.getElementById('__vue-devtools-component-inspector__name__')?.textContent?.includes('<Home>'))
      await target.click()
      await input.locator('[data-component-pin]').waitFor()
      if (await input.textContent() !== 'Check Home this')
        throw new Error(`Page selection did not preserve cursor and draft: ${await input.textContent()}`)
      await page.screenshot({ path: `/tmp/devtools-page-picker-${width}.png` })
      await pick.click()
      await page.getByRole('button', { name: 'Cancel component selection', exact: true }).waitFor()
      await target.hover()
      await page.keyboard.press('Escape')
      await pick.waitFor()
      if (await input.locator('[data-component-pin]').count() !== 1)
        throw new Error('Cancelling changed component pins')
      await input.fill('@')
      const group = page.getByRole('group', { name: 'Components', exact: true })
      await group.getByRole('option').first().waitFor()
      if (await group.getByRole('option').count() !== 20)
        throw new Error('Component candidates are not limited to 20')
      await input.fill('@hm')
      const home = group.getByRole('option').filter({ hasText: '<Home>' })
      await home.waitFor()
      await page.waitForFunction(() => document.getElementById('__vue-devtools-component-inspector__name__')?.textContent?.includes('<Home>'))
      await page.screenshot({ path: `/tmp/devtools-component-mention-${width}.png` })
      const popup = await page.locator('.acp-suggestions').boundingBox()
      const editor = await input.boundingBox()
      if (!popup || !editor || popup.x < 0 || popup.y < 0 || popup.x + popup.width > width + 1 || popup.y + popup.height > editor.y + 1)
        throw new Error('Component menu is clipped or overlaps the editor')
      await input.press('Enter')
      await page.waitForFunction(() => document.getElementById('__vue-devtools-component-inspector__')?.style.display === 'none')
      const pin = input.locator('[data-component-pin]')
      if (await pin.count() !== 1 || await pin.getAttribute('contenteditable') !== 'false' || (await input.textContent()).includes('@<Home>'))
        throw new Error('Component reference is not an inline atomic pin')
      if (await pin.locator('button, [data-remove-reference]').count())
        throw new Error('Component pin still contains action buttons')
      const bounds = await pin.boundingBox()
      if (!bounds || Math.abs(bounds.height - 28) > 1 || bounds.width > 80)
        throw new Error(`Component pin has unexpected height or excess width: ${JSON.stringify(bounds)}`)
      await pin.click()
      await page.waitForFunction(() => document.getElementById('__vue-devtools-component-inspector__')?.style.display !== 'none')
      await page.screenshot({ path: `/tmp/devtools-component-pin-${width}.png` })
      if (await page.getByRole('button', { name: 'Send message', exact: true }).getAttribute('aria-disabled') === 'true')
        throw new Error('Component references cannot be sent')
      await input.focus()
      await input.press('End')
      await input.press('Backspace')
      await input.press('Backspace')
      if (await pin.count())
        throw new Error('Keyboard deletion did not remove the component pin')
      await input.fill('@Panel39')
      await group.getByRole('option').filter({ hasText: '<Panel39>' }).waitFor()
      await input.press('Escape')
      await page.waitForFunction(() => document.getElementById('__vue-devtools-component-inspector__')?.style.display === 'none')
      await input.fill('@')
      await group.getByRole('option').nth(2).hover()
      await page.waitForFunction(() => document.getElementById('__vue-devtools-component-inspector__name__')?.textContent?.includes('<Panel1>'))
      await input.press('ArrowUp')
      await page.waitForFunction(() => document.getElementById('__vue-devtools-component-inspector__name__')?.textContent?.includes('<Home>'))
      await input.press('Escape')
      console.log('PASS component references', width, height)
    }
    if (errors.length)
      throw new Error(errors.join('\n'))
  }
  finally { await browser.close() }
}
main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
